// Code generaTed by fileb0x at "2022-03-06 23:48:01.072189 +0800 CST m=+0.130649680" from config file "b0x.yaml" DO NOT EDIT.
// modified(2021-06-28 19:10:38 +0800 CST)
// original path: swagger-ui/new/robots.txt

package swaggerFiles

import (
	"os"
)

// FileRobotsTxt is "/robots.txt"
var FileRobotsTxt = []byte("\x55\x73\x65\x72\x2d\x61\x67\x65\x6e\x74\x3a\x20\x2a\x0a\x44\x69\x73\x61\x6c\x6c\x6f\x77\x3a\x0a")

func init() {

	f, err := FS.OpenFile(CTX, "/robots.txt", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileRobotsTxt)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
